### ISSUE TITLE
Food Data CSV Upload

### ISSUE THREAD

**Issue by rsial2** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#144] opened 2016-11-05 00:15 UTC
When importing a new food data.csv file, automatically delete the old version first. We are having too many issues with duplicate food items appearing after importing a new food data file.  We will always be uploading a complete data.csv file and never just a few foods at a time.  Also, take away the function of the column in the data.csv file that indicates Deleted=YES or NO.

**Comment by coderReview** [comment] 2016-11-24 03:41
This is my solution, please advise if it's acceptable:
1- Modified the load food script to avoid duplication. Example:
"Food with Name" == "Food w/ Name" == "Food w/Name" == "Food W/ name "
"Food and Drink" == "Food & Drink" == "food and drink""
2- Added a checkbox on import screen to remove all foods and food records before loading the new food as requested in the ticket.  Please beware that when doing this, the IFIT iPad app must be reinstalled in all devices.

**Comment by szwart** [comment] 2016-11-28 16:20
The modified load food script might help...but we don't think #2 will work.  We can't have the FIT app have to be reinstalled each time we update the food list.  Is there any other way to reload a new food list without having to reinstall?  We understand there may be old foods left on the Daily Intake Summary reports from previous days that will no longer be in the database, but it's fine to keep them.

**Comment by coderReview** [comment] 2016-11-28 18:34
When food is removed from list it makes no sense keeping any records associated. I can try to figure out a way to flag the iPad app to clear all its data before loading the new food list. Is this better ?

**Comment by szwart** [comment] 2016-11-28 18:56
If a crewmember eats Food A on GMT 100 and we upload a new food database on GMT110 and Food A is no longer in the database, we would still want to know that they ate Food A during their mission.  

If the app cleared all of its data before loading the new food list, would it automatically download all data from all users so there is no chance of losing data?  Our only concern is that a crewmember might want to look back at the previous months’ data, but if there is no way to avoid this, then we are OK with clearing the data.

**Comment by coderReview** [comment] 2016-11-29 17:42
> If a crewmember eats Food A on GMT 100 and we upload a new food database on GMT110 and Food A is no longer in the database, we would still want to know that they ate Food A during their mission.

This is only possible if the food is not removed from the Database. 

> Our only concern is that a crewmember might want to look back at the previous months’ data,

That is why we were using the deleted column. To allow the visualization of removed food records. I think we can improve our loading script to avoid as much as possible to have duplicated food.

I think this way we can keep the data safe and avoid the duplicate issues. Right now I've already changed the script to improve data loading. And created a function to check for similar names as shown in the previous post.

Now the function will match food with following characteristcs:
1- Case insensitive: Apple Juice == apple juice
2- Space insensitive: Apple & Banana == apple&banana
3- Abbreviation (with, w/ - and, &): Apple with Banana == Apple w/ Banana; Apple and Banana == Apple & Banana

This is really important when deleting a food. One other way of doing the update is:
1- Using the last CSV file, mark all as deleted
2- Create a new CSV file with new data. 
3- Concat file 2 into file 1. If the food matches an existing food (using the above rule) it will remove the deleted flag. If not a new food is added.
Using this procedure we can guarantee no duplicated food will exists and all data is preserved.

**Comment by szwart** [comment] 2016-11-29 18:32
We’ve tried using the deleted feature, but found it to not work consistently well.  The order of the deleted food mattered, and sometimes the food list got sorted and maybe that is why deleted items showed up.  When we would go back and test foods we mark as deleted they still showed up in the food list in the app, even after we go back and sort the csv file with all deleted items at the top of the list.   And at least one occasion during testing we uploaded a new csv file with a new food item and the food item appeared in the admin tool but never appeared in the app.  We will need to update foods regularly due to new food lots and different nutrient contents.  If we have a list that grows quite long (a few thousand lines long), will that slow down the speed of the app?

We are willing to try the deleted feature again if you think this is the best way to go.

**Comment by coderReview** [comment] 2016-11-29 19:49
@szwart The amount of items won't be an issue.  But I can keep the database wipe out when you want to restart from scratch (will need to reinstall the app).

But my proposal is to keep the delete food functionality and I work with you to get it running correctly.

What did you think of the procedure I've sent. I can even make step 1 automatic. When you upload a new file, I will mark all existing food as deleted, if you want to keep it in the App, the new file being sent must have that food. Even if it name does not match exactly the existing food, you won't get duplicated records. I think this is a good solution.

You won't have to worry about the deleted flag. You only sent in the CSV file the food you want to show in the app.

**Comment by szwart** [comment] 2016-11-30 15:02
Thanks Paulo. OK, I think we are hesitantly ok with this plan…we will need to test this one quite a bit to make sure we know all of the nuances to uploading new food databases.

**Comment by coderReview** [comment] 2016-12-07 11:40
@rsial2 this is fixed. Will commit the code.

**Comment by coderReview** [comment] 2016-12-10 05:33
Code committed

**Comment by nithyaasworld** [comment] 2017-01-23 07:17
@coderReview 

1.--> Now whenever a new food data is loaded, all previous data will be marked as deleted. So there is no use of the checkbox "Mark existing food as deleted". So can we please remove this checkbox to avoid any confusions?

2--> I uploaded this food data file. There are only two food items. The first one is new entry, second one is already existing data. After uploading, it showed me the message Bulk upload success. But the new food entry is not found in the Food data.

Can you please check this?
[food_data.csv.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/722842/food_data.csv.zip)

**Comment by coderReview** [comment] 2017-01-23 11:40
1- that is not true. If you don't mark all as deleted, existing food will be kept. Only the ones in the new food file will get updated 
2- will check

**Comment by nithyaasworld** [comment] 2017-01-23 16:49
Ok. Can you please update me on No:2 issue?

 (Only then, I can thoroughly verify #142)

**Comment by coderReview** [comment] 2017-01-29 13:56
The data in CSV is incorrect.

Should be like this:

```
Food Product Name,Category,Origin,Barcode,Fluid,Energy,Sodium,Protein,Carb,Fat,Profile Image,Deleted,1
Artic Char Jerky Chips,Meat / Fish,CSA Foods,,4.38,114.22,599.65,16.996,1.995,3.999,,NO,
```

You need one more column.

**Comment by nithyaasworld** [comment] 2017-01-29 14:21
Ok. Can you please update the sample template here in the link (screenshot), so I will take the sample template from there? Thanks.


![image](https://cloud.githubusercontent.com/assets/5114190/22404693/44f9163a-e65c-11e6-9506-8e4e1099e10d.png)

**Comment by coderReview** [comment] 2017-01-29 14:25
@nithyaasworld done

**Comment by nithyaasworld** [comment] 2017-01-29 16:38
@coderReview What does the last column with value "1" imply?

**Comment by nithyaasworld** [comment] 2017-01-29 17:12
4--> Can I have a list of existing food entries in CSV format? is it possible?
(I am asking this, in order to check, "Mark existing food as deleted" function. I do not want to delete all 933 entries that are present now)

**Comment by nithyaasworld** [comment] 2017-01-29 23:02
5-->I uploaded the data.csv file with an entry "Jan 30 Test 01" at line 491. It showed the message "Bulk upload successful" but this entry was not found.

6--> Also there are 926 entries in the Food Data tab now. But in the csv file, I had only 491 food items. Since I had checked "Mark existing food as deleted", I expected only the items in the csv file to be present in the Food data tab and not 926 entries.

Uploaded data: 
[data.csv.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/737892/data.csv.zip)

(Please check No:3,5,6 for this ticket. 1,2 and 4 are resolved)

**Comment by coderReview** [comment] 2017-01-30 11:39
@nithyaasworld please try again.

**Comment by nithyaasworld** [comment] 2017-01-30 12:38
Now after I have uploaded a data.csv file with 491 entry, i could see only 25 entries.
During the import, "Mark existing entry as deleted" checkbox was checked.

Expected: There should be 491 food records as in the uploaded file.

uploaded data: 
[data.csv.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/738900/data.csv.zip)

**Comment by coderReview** [comment] 2017-01-31 01:16
@nithyaasworld The problem was not with the code. But inconsistency in the database. Please try again.

@rsial2 and @szwart when you deploy this new code, are you going to do it on a fresh system (user and food database)? Otherwise, we might need to treat this inconsistency.

**Comment by nithyaasworld** [comment] 2017-01-31 04:08
Food data gets uploaded now. After uploading, all old data are removed and it has the same data as uploaded via CSV file.

If there is any duplicate food item present in csv, then only the latest food item is added.

I will verify what happens to removed food items in iPad app and update here.

**Comment by nithyaasworld** [comment] 2017-01-31 11:27
Removed food items are still shown in iPad app, which is as expected.

@coderReview

 I have deleted all data in Food tab of Admin Tool except two food entries. But still all food entries appear in my iPad Add-consumption Food list. I will check if this is  because my iPad is 24 minutes faster.

**Comment by nithyaasworld** [comment] 2017-01-31 11:31
> I have deleted all data in Food tab of Admin Tool except two food entries. But still all food entries appear in my iPad Add-consumption Food list. I will check if this is because my iPad is 24 minutes faster

Set correct time in iPad. Still the same issue exists.

**Comment by coderReview** [comment] 2017-01-31 12:11
@nithyaasworld now that you corrected the time, can you import the food CSV again and sync the iPad? Just correcting the time won't fetch new data since you synchronized with the incorrect time. Thanks

**Comment by nithyaasworld** [comment] 2017-01-31 12:22
Imported the food csv again and synced the iPad. Still the same. I see all Food items in Add-Consumption list.

**Comment by szwart** [comment] 2017-01-31 13:32
When we deploy this new code, we will not be doing it on a fresh system unfortunately.

**Comment by coderReview** [comment] 2017-02-02 00:00
@nithyaasworld the database is now in an inconsistency state. I have removed some Food Products that were not supposed to be removed. Therefore the iPad devices does not know that these food products must be removed from their database. 

I just have to fix one small issue with the database and you can start a fresh test. Will let you know when it's done.

Test Scenario:
1- Remove iPad app
2- Sync with food
3- Upload food csv file
5- Check iPad app food inventory
6- Upload a second food csv file
7- Check iPad app food inventory

Thanks

**Comment by nithyaasworld** [comment] 2017-02-02 09:44
@coderReview Ok. I will wait.

**Comment by coderReview** [comment] 2017-02-04 02:54
@nithyaasworld done. You can test.

**Comment by nithyaasworld** [comment] 2017-02-04 06:08
@coderReview There are 744 entries in Food tab (in admin tool) currently. I have food data of around only 480 entries (the csv file you shared with me for testing another ticket).. Can I upload this 480 and replace the existing 744 entries? would we lose data?

Or can you share the CSV with current 744 entries?

Thanks.

**Comment by nithyaasworld** [comment] 2017-02-04 06:23
@coderReview Thanks for sending the file.

I will Verify this.

Meanwhile, can you please remove the last column "1" from the Food CSV file? I remember it was not present during the last test cycle.

**Comment by coderReview** [comment] 2017-02-04 06:24
@nithyaasworld the column 1 is normal. Don't worry about this.

**Comment by nithyaasworld** [comment] 2017-02-04 07:25
Ok.

I tried Uploading a new csv with just 3 food items and marked all existing as deleted during the upload. It is success and showed only the 3 food items in Admin Tool.

But in iPad, I still see the long list of food items along with the 3 newly added food items. I logged out and logged in again and tried. I closed the app and re-opened and tried.

It seems like iPad Food inventory shows Deleted Food products too.

Please check.

**Comment by coderReview** [comment] 2017-02-04 12:26
@nithyaasworld have you deleted the app from the iPad. 1st step.

> 1- Remove iPad app
2- Sync with food
3- Upload food csv file
5- Check iPad app food inventory
6- Upload a second food csv file
7- Check iPad app food inventory

**Comment by nithyaasworld** [comment] 2017-02-04 13:37
Ok. Its working after re-installing the app.

I am checking in detail. Once done, I will update.

**Comment by nithyaasworld** [comment] 2017-02-04 14:07
When I change the category of a Food item (in the uploaded csv file), it shows two items in iPad. Both old item and new item.

Whereas in Admin Tool, it shows only the latest Food item.

![image](https://cloud.githubusercontent.com/assets/5114190/22619018/2bef6a04-eb11-11e6-8343-430805c45b61.png)

![image](https://cloud.githubusercontent.com/assets/5114190/22619025/449f0a32-eb11-11e6-8880-7a9abbe4e77c.png)

**Comment by coderReview** [comment] 2017-02-04 14:34
Will check. The end result is to have two food items. Because changing the origin the app should understand as a new food.
Just to understand.
You created a CSV and uploaded to server. And then changed the origin and uploaded it again. Right?

**Comment by nithyaasworld** [comment] 2017-02-04 15:05
The Food named "Food One" was uploaded via CSV initially. Then again modified the category (by mistake) via another CSV upload.

The Food named "Manually Adding01" was created in iPad. Then I remember adding all nutritional and category via the Admin Tool. then I again used the same data in CSV and uploaded.

**Comment by coderReview** [comment] 2017-02-04 20:38
Let's see what is going on:

1- There are two entries in database for **Food One**. One with **removed = false** and another **removed = true**. Thus the Admin Tool is showing the correct information. iPad not.
2-  There are two entries in database for **Manually Adding01**. One with origin **null** and another with origin  **ESA Foods**.  The one with origin null is an Adhoc Food, therefore it doesn't appear in the Admin Tool, only in iPad app and for the user who created it.

I will check why the iPad is showing two versions of Food One. It should show only the one with **removed = false**.

@nithyaasworld, @rsial2 and @szwart please let me know if don't agree with what I said.

**Comment by coderReview** [comment] 2017-02-04 21:44
@nithyaasworld 
1- are you still seeing two entries for Food One and Manually Adding01?

**Comment by nithyaasworld** [comment] 2017-02-05 01:43
@coderReview 

Yes. I am still seeing two entries for both the food products.

> 1- There are two entries in database for Food One. One with removed = false and another removed = true. Thus the Admin Tool is showing the correct information. iPad not.

I agree.

> 2- There are two entries in database for Manually Adding01. One with origin null and another with origin ESA Foods. The one with origin null is an Adhoc Food, therefore it doesn't appear in the Admin Tool and should not appear in food list in iPad.

Actually I added an Adhoc food and updated the same Adhoc food in Admin Tool. So in Ipad, I would still expect Only one entry as I have just updated the existing adhoc food via admin tool.

**Comment by nithyaasworld** [comment] 2017-02-05 02:43
3--> I added a new food via Snap-a-Photo option.
Then I uploaded a new set of food items via CSV file. So this food item added by Snap-a-photo option was removed from Admin Tool (This is expected).

In iPad, Food Name added by Snap-a-photo option disappeared too. 

This happens only for the food added by Snap-a-photo option. There is no such problem with food items added by Adhoc option.

![image](https://cloud.githubusercontent.com/assets/5114190/22623279/e365545a-eb7a-11e6-8d29-a2d1b2c02e64.png)

**Comment by coderReview** [comment] 2017-02-05 15:01
@nithyaasworld did you retest this one?

**Comment by nithyaasworld** [comment] 2017-02-05 16:12
When I verified in the morning, it was ok.

I will verify once again all the issues reportedly previously and update.

**Comment by nithyaasworld** [comment] 2017-02-05 17:56
@coderReview I have one last question for this ticket.

You have already confirmed that food added via adhoc will not appear in Admin Tool.

Can you also confirm if food added via "snap a photo" option will not appear too in Admin tool?

**Comment by coderReview** [comment] 2017-02-05 19:06
Confirmed. Any food added in the iPad app won't appear in Admin Tool.

**Comment by nithyaasworld** [comment] 2017-02-05 19:33
**Test Summary:** 

> Now the function will match food with following characteristics:
> 1- Case insensitive: Apple Juice == apple juice
> 2- Space insensitive: Apple & Banana == apple&banana
> 3- Abbreviation (with, w/ - and, &): Apple with Banana == Apple w/ Banana; Apple and Banana == Apple & Banana

Verified

> If a crewmember eats Food A on GMT 100 and we upload a new food database on GMT110 and Food A is no longer in the database, we would still want to know that they ate Food A during their mission.
 
Verified. Removed Food item will still appear in Food Consumption list (in iPad) if the crewmember has already consumed it.


> When importing a new food data.csv file, automatically delete the old version first. We are having too many issues with duplicate food items appearing after importing a new food data file

Verified. When importing a new food data, if "mark existing food as deleted" option is selected (it is selected by default), then all old food data will be marked as "removed" and all new food data will be added.

When importing a new food data, if "mark existing food as deleted" is  not selected, then it will not delete the existing food items. It will add the new ones and update the old ones.

Verified that Removed Food items do not appear in iPad's Food Inventory list.

Verified that there is no duplicate of food items when adding new foods.

**Closed** 2017-02-13 23:31 UTC
Labels: QA Verified, Round 12
