### ISSUE TITLE
Round 10 - Food Inventory

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#111] opened 2016-03-18 18:53 UTC
We have noticed that whenever we have a food item in the data.csv file that is deleted (indicated by a YES in the Deleted column), then the second entry for that food item that is not deleted (indicated by a NO in the Deleted column) appears twice in the Food Inventory.  Example: Pork w/Potatoes appears twice in the Food Inventory.

**Comment by coderReview** [comment] 2016-03-23 18:51
@szwart Was the file you've sent me loaded in an empty database or did you load a previous file? I see that you have lot of duplicated entries with YES and NO deleted columns. If you want to update a food you don't need to delete it first. Just update the values in the existing row.

**Comment by szwart** [comment] 2016-03-23 18:55
Whenever we get a new formulation of an existing food (or whenever the package size is changed), we create a new line and type YES in the deleted column for the outdated food item.

In the future, should we never have 2 identical food names even though one is deleted?

**Comment by coderReview** [comment] 2016-03-23 20:29
@szwart When I've developed the application the idea was to update the existing row. However, it doesn't mean that having more rows related to one Food item won't work. In theory, the only restriction is that the new entry are after (below) the old entries for a given Food item. I will simulate this scenario and will give you a feedback.

**Comment by coderReview** [comment] 2016-03-23 21:21
I've made some tests and could not reproduce this issue. Only one item is listed.
I've loaded the file without any food deleted. There 745 food items. I then applied the sent csv file. The result count is 740 food items.

**Comment by rsial2** [comment] 2016-03-28 17:27
Hi @szwart, can you please confirm that I can close this ticket.

**Closed** 2016-03-28 17:29 UTC
Labels: Round 10
