### ISSUE TITLE
Data Sync with Admin Tool 

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#138] opened 2016-08-24 16:11 UTC
While testing ISS FIT in a ground analog where 4 users used 4 different iPads all syncing to the same server, we noticed that the day 1 data were not all 100% synced on all 4 iPads.  For example, User 1's iPad showed 10 food items were logged but when we went to User 2's iPad and looked at User 1's data, there were only 8 items logged.  When we looked at User 3's iPad and looked at User 1's data, there were even less items logged.  Is there a loop issue or counter issue in the code when iPads are syncing?  Can we double check this please?

**Comment by coderReview** [comment] 2016-08-24 17:28
@szwart only the 1st day data had issues?
I have a few other questions to help me understand the issue.
Are there clocks correct? 
Are they in the same timezone?
Who logged the food records?
Were the sync of the other iPads done on the same day?

**Comment by coderReview** [comment] 2016-08-24 17:28
A step by step of how did you test would be nice if possible. Thank you

**Comment by szwart** [comment] 2016-08-24 18:19
Yes - all in the same timezone. 4 separate users during the same study while living in a chamber here at NASA.  They each had their own iPads and logged their foods on their own iPads.  They all synced with the server at the same times.  The only way we noticed this was when we were going back to look at nutrient data from the study (they lived in the chamber for 30 days).  One of the iPads had very little battery life left, so we looked at a different iPad to get the nutrient data from the iPad that was about to die.  We did not check every single day, but did check most other days.  The attached photos are examples of 2 iPads with data for the same subject on the same day but different lists of food.
 
![cdr1](https://cloud.githubusercontent.com/assets/11872594/17942454/109cd4e8-69fd-11e6-915a-999c1ee287c8.jpg)
![fe](https://cloud.githubusercontent.com/assets/11872594/17942455/12f21514-69fd-11e6-8168-9e4eeae7b10e.jpg)
![ms1](https://cloud.githubusercontent.com/assets/11872594/17942462/14f87e48-69fd-11e6-8635-9a159698d4aa.jpg)

**Comment by coderReview** [comment] 2016-10-25 20:14
@szwart
1- Is there any possibility you could share a dump of the database used during this tests? 
2- Just to confirm again, the issue is just with the data in the first day.
Thanks

**Comment by rsial2** [comment] 2016-10-25 20:24
@nasarader can you help with the request above please?

**Comment by szwart** [comment] 2016-10-25 20:28
You are looking for the food data file?  Or the user data?  Or both?

**Comment by coderReview** [comment] 2016-10-25 20:31
Is the postgresql database still available to you? I need the data from food_product_record, food_product and nasa_users tables - if possible.

**Comment by rsial2** [comment] 2016-10-25 20:51
hi @coderReview, unfortunately @szwart will not be able to directly provide it.

@szwart & @nasarader would be able to speak with the folks who own the database and get us a copy? Please feel free to obfuscate any PII.

**Comment by szwart** [comment] 2016-10-26 13:26
FYI - I've requested the data you need from the folks who worked that mission.  I'll keep you posted.

**Comment by rsial2** [comment] 2016-10-26 21:18
Hey @szwart any luck with this? Sorry to rush - but we can't complete delivery until we get it, so we'll need to delay the delivery until we do.

CC @coderReview & @nasarader

**Comment by szwart** [comment] 2016-10-27 15:47
No, unfortunately not. Will try to see if anyone else can help.

On Oct 26, 2016, at 4:18 PM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @szwart<https://github.com/szwart> any luck with this? Sorry to rush - but we can't complete delivery until we get it, so we'll need to delay the delivery until we do.

CC @coderReview<https://github.com/coderReview> & @nasarader<https://github.com/nasarader>

**Comment by rsial2** [comment] 2016-11-07 18:49
@coderReview were you able to continue working on this, or do you still need the database dump?

**Comment by coderReview** [comment] 2016-11-08 10:43
I was able to finish this. I've implemented a fix looking at how the code is working right now.
The best way to test it is to have all 4 existing users in our test environment using the application at the same time for 30mins. Do you think we can try that out?

**Comment by szwart** [comment] 2016-11-08 13:23
I’m up for trying that.  I will be at my desk most of the day.

**Comment by coderReview** [comment] 2016-11-08 15:24
@szwart 
Due to timezone difference I am only available after 6pm EST.

**Comment by szwart** [comment] 2016-11-08 15:54
Are you available tomorrow at all?

**Comment by coderReview** [comment] 2016-11-08 15:55
@szwart 
Also, only after 6pm EST.

**Comment by szwart** [comment] 2016-11-08 16:01
OK.  I can be available after 6:30pm EST today, or after 6pm EST tomorrow.  Do we have 2 other users that could be available?  Holly is not available in the evenings.  I can load to my home iPads if needed...

**Comment by coderReview** [comment] 2016-11-08 16:03
@szwart 
I can run in my device and simulator at the same time.

**Comment by szwart** [comment] 2016-11-08 16:08
OK - I will load the HockyApp to my home iPad tonight and will need you to add that device as a user.  Then maybe we can test tomorrow evening from 6:00-6:30pm EST?

**Comment by coderReview** [comment] 2016-11-08 16:10
Ok. Just add the device in the hockeyapp so I can create a new build with your UDID.

**Comment by rsial2** [comment] 2016-11-09 16:26
Just want to confirm. Are you guys (@coderReview & @szwart) going to test today at 6 PM EST?

**Comment by szwart** [comment] 2016-11-09 16:30
Yes, that is the plan.

**Comment by coderReview** [comment] 2016-11-09 16:38
@szwart 
I will prepare a new build with your device.

**Comment by coderReview** [comment] 2016-11-09 22:02
@szwart 
New version was sent to you

**Comment by coderReview** [comment] 2016-11-09 22:09
Can you tell me if you are available for testing?

**Comment by rsial2** [comment] 2016-11-10 19:28
Paulo, how did this go? Were you able to resolve it?

**Comment by coderReview** [comment] 2016-11-11 18:39
@szwart 
One of your devices last sync was 11:20pm GMT (black one). 
Can you open this device again, let it sync and get the pictures? I've added/updated one food after 11:20pm GMT and it's not showing properly.
Thanks

**Comment by coderReview** [comment] 2016-11-11 18:41
I will look at the data of the white one and with mine.
Thanks

**Comment by coderReview** [comment] 2016-11-11 18:43
Also, you might need to scroll down some to get all foods for a given day.

**Comment by coderReview** [comment] 2016-11-11 18:44
Let's do the following. I will prepare an excel list based on the database and send it to you. You can check against the data in your iPads. Thanks

**Comment by szwart** [comment] 2016-11-14 15:49
Paulo,

I apologize for the lag – I was out of the office on Friday.  I noticed that one of the iPads stopped syncing at 11:20 (the error message came up indicating that I was not connected to the server anymore) when I was at home.  I just tried connecting that iPad to the nasa wifi and I’m able to connect just fine, but I’m still getting the error message.  I tried connecting using my phone’s hotspot and it showed I was connected, but I’m still getting the error message.  I’m able to go to other websites, so I know that I’m connected.  Do you have any suggestions?

Last week, I was able to connect to the food database using the nasa wifi, so I’m not sure what has changed.

**Comment by coderReview** [comment] 2016-11-16 19:21
@szwart 
Can you post a screenshot of the error when you try to login in the application? I've checked the server and it's running ok.
Thanks

**Comment by szwart** [comment] 2016-11-16 19:25
I'm getting the white box that pops up saying "Error We are unable to sync this iPad with the central food repository. Don't worry!  You can still use the ISS FIT app and we will attempt to sync with the central food repository when it is available."  I just tried again and it's giving me the same message.  I've confirmed that I'm connected to wifi because I can go to other sites.

**Comment by szwart** [comment] 2016-11-16 20:43
With the new build (1.7) I am not getting that error message anymore and my iPad is syncing just fine.

**Comment by coderReview** [comment] 2016-11-16 20:57
Good. Will provide the records list so we can check.

**Comment by coderReview** [comment] 2016-11-17 22:45
@szwart 
Here is the file with the report for all users and the 3 days of testing (9/11, 10/11 and 11/11). Can you check against the data in your iPads?

[test_summary.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/598652/test_summary.zip)

**Comment by szwart** [comment] 2016-11-18 15:03
Paulo,

Under the Charlton Heston user, Bran Chex appears on the 3rd line of the excel spreadsheet, but that item does not appear on the iPads.  For Jack O’Neal, there is an Apple Cranberry Drink consumed on 11/9/2016 23:00 but it does not appear on the iPad displays.

I noticed that many of the foods don’t appear in the same order as they appear on the iPad.

Let me know if it would help to have another session where we simultaneously add foods.

Thanks,
Sara

**Comment by coderReview** [comment] 2016-11-18 15:14
@szwart 
Thank you. I will fix the ordering in iPad app. Will check what happened with the food records.

**Comment by coderReview** [comment] 2016-11-18 15:20
@szwart 
Looking at your photos, I could find Bran Chex on day 314 (this is for the black device). For the white one, you would need to scroll to check that. On my iPad this food appeared correctly.

As for the "Apple Cranberry Drink" I will check what is going on.
Thanks

![314_rashid_helston](https://cloud.githubusercontent.com/assets/5925442/20434952/48dd2f2e-ad91-11e6-9b0d-551bcf10a280.JPG)

**Comment by szwart** [comment] 2016-11-18 15:28
There was another Bran Chex that appeared in the excel file for that day, consumed at 23:00, that does not appear on the iPads.

**Comment by coderReview** [comment] 2016-11-24 03:32
There was an issue with the report. It was showing deleted Food Record. Fixed that.
Please check the new attached file. thank you.
[summary (1).zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/610428/summary.1.zip)

**Comment by szwart** [comment] 2016-11-28 20:49
I checked my home iPad and everything matched.  I wasn't able to check my work iPad b/c it had already been upgraded to the next version and the data were wiped out.

**Comment by rsial2** [comment] 2016-11-29 19:57
@coderReview do you need to do anything with this item, or are we all set?

**Comment by rsial2** [comment] 2016-12-05 17:29
Please confirm Paulo.

**Comment by coderReview** [comment] 2016-12-07 11:31
@rsial2 no. We are ok.

**Comment by nithyaasworld** [comment] 2017-01-23 19:44
There is no Data sync issue as of now. Tested with a device and a simulator. 

I will keep watching the data-syncing until other tickets are closed.

@coderReview Can you please make the food order same in all device for a user? 

![image](https://cloud.githubusercontent.com/assets/5114190/22219835/60160df8-e1d2-11e6-9c5b-3c324297f26d.png)

**Comment by nithyaasworld** [comment] 2017-01-24 12:43
2--> (I am able to use mic icon in the simulator there is no crash. )

I added 4 items via my iPad and logged out. When I logged in via simulator, those 4 items were present. Now I added 2 more items via simulator (one of them is through mic entry) and logged out. I re-logged in simulator and verified that there were 6 entries now.

Now I again logged in to my iPad, but found that only 4 entries were present. The two entries entered via simulator is not appearing in my iPad.

(I assume that synching happens whenever user logs out).

user tested with: DeleteUser Testing

![image](https://cloud.githubusercontent.com/assets/5114190/22247601/af14f6ec-e260-11e6-9145-6f7126c75988.png)

**Comment by coderReview** [comment] 2017-01-24 20:19
2- How did you enter the two last items after the first 4 and their timestamp is before?
@nythiaasworld

**Comment by nithyaasworld** [comment] 2017-01-25 03:48
2 -- Ok. I just checked. My iPad's time is 24 minutes faster than my iMac. I think it should still get synced even if the timestamp is in the past.

**Comment by coderReview** [comment] 2017-01-25 08:48
2- How did you enter the two last items after the first 4 and their timestamp is before?
@nythiaasworld

**Comment by coderReview** [comment] 2017-01-26 14:46
@rsial2 can you confirm that the app should cope with time differences of the iPad devices?

**Comment by rsial2** [comment] 2017-01-26 14:57
I don't know @coderReview. I'm assuming all of the iPads are in the same time zone.

@szwart what are your thoughts?

**Comment by szwart** [comment] 2017-01-26 15:54
Cheryl confirmed that the time zones on ISS for the SSC laptops and the iPads are all synched or set to Reykjavik time.

On Jan 26, 2017, at 8:58 AM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know @coderReview<https://github.com/coderReview>. I'm assuming all of the iPads are in the same time zone.

@szwart<https://github.com/szwart> what are your thoughts?

**Comment by coderReview** [comment] 2017-01-26 16:06
The main issue is not time zone difference. But just wrong time. If the devices and the backend server are synced to a central time server there won't be any problem. Should I take any action or can we leave like this?

**Comment by coderReview** [comment] 2017-01-26 16:11
There is a 10min tolerance.

**Comment by szwart** [comment] 2017-01-26 16:46
What would happen if one iPad was an hour off for whatever reason (anything beyond the 10 min tolerance). Would we lose some data from that iPad?

On Jan 26, 2017, at 10:07 AM, Paulo Vitor Magacho <notifications@github.com<mailto:notifications@github.com>> wrote:


The main issue is not time zone difference. But just wrong time. If the devices and the backend server are synced to a central time server there won't be any problem. Should I take any action or can we leave like this?

**Comment by coderReview** [comment] 2017-01-27 10:22
There is no data loss. Just the data would not get synchronized to the other devices that are ahead of time.

**Comment by szwart** [comment] 2017-01-27 14:08
OK – as long as no data loss when we pull a report, we are good with this.

**Comment by nithyaasworld** [comment] 2017-01-27 16:55
I will check this one more time, after all the issues related to Reports are verified.

**Comment by coderReview** [comment] 2017-02-04 02:55
@nithyaasworld i think you can retest.

**Comment by nithyaasworld** [comment] 2017-02-06 04:51
@coderReview I am not able sync my simulator to the Central Repository.
No such problem with iPad 

This is the steps performed:
1- Open simulator and login as jan23test1 user
(it gave me an error msg stating that user is already logged in another device)
2- I opened iPad and logged out from jan23test1 user
3- Now in simulator, i Logged in as jan23test1 user and added one food item
4- Clicked logout
5- It gave me an error message stating that "we are unable to sync this ipad"

(I kept trying about 5 times- logging in and Logging out - I am getting the same unable-sync-error message)

Please look into this.

![image](https://cloud.githubusercontent.com/assets/5114190/22635056/e0080b50-ec55-11e6-855a-f6599840e9a9.png)

**Comment by nithyaasworld** [comment] 2017-02-06 04:56
simulator log: 
[system.log.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/753664/system.log.zip)

**Comment by nithyaasworld** [comment] 2017-02-06 12:17
Tried one more time now. Same results.

[system.log.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/754528/system.log.zip)

**Comment by nithyaasworld** [comment] 2017-02-07 09:17
Thanks Paulo for helping with this!

Verified. There is no sync issue now. Sync between my device and simulator (both with same time settings)  are instant now.

**Comment by nithyaasworld** [comment] 2017-02-07 09:35
Paulo ~ 

I just set my device time as 1 hour 15 minutes ahead of the actual time. My simulator has actual correct time.

In my device, I added a food item at around 16:10. This added item appeared in simulator where it was only 14:55.

However, when I added a food item via the simulator, it is not appearing in my iPad. My iPad is already ahead of the actual time. So expecting the added food item via simulator to be available on iPad.

(This added item is synced to db and available via Report too)

**Comment by coderReview** [comment] 2017-02-07 12:27
If your device is ahead 1:15h, when you add anything in simulator you will have to be at least 1:15h without synchronizing to server. That is because the app uses local time (in GMT timezone) to save the last sync time.
If the iPad is synchronizing the sync time is always ahead and won't fetch any change made by simulator. However all devices at NASA are synchronized  to a central server. So that is not an issue, as confirmed by @szwart
Also all times in the app are GMT time.

**Comment by nithyaasworld** [comment] 2017-02-07 12:39
Ok. Thanks.

**Comment by nithyaasworld** [comment] 2017-02-10 04:32
@coderReview 

> szwart: What would happen if one iPad was an hour off for whatever reason (anything beyond the 10 min tolerance). Would we lose some data from that iPad?
> coderreview: There is no data loss. Just the data would not get synchronized to the other devices that are ahead of time.
> 

I tested the below scenario considering the above fact.

In iPad, I have my device time setup as 1.15hrs ahead of actual time.
In simulator, I have actual time.

I created a new user via iPad and added some food products to it, then logged out (they all got synced now). Now back in simulator, I logged in as the same user and found that all food products are synced. Now I added another food item via simulator and logged out. (there is no error, meaning it got synced successfully)

Now I logged in iPad, found that it is not getting synced now. Once I used the same user in simulator, my iPad is not syncing at all (for any user). that is, any data I add in iPad for any user, it is not getting synced. I get error "We are unable to sync this iPad with..."

**Comment by coderReview** [comment] 2017-02-10 04:43
Can you get the logs from the iPad device?

**Comment by nithyaasworld** [comment] 2017-02-10 12:01
Please find the log: 
[console log.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/766575/console.log.zip)

**Comment by coderReview** [comment] 2017-02-10 18:37
@nithyaasworld iPad device was not completely synchronized. It seems to be missing some food information. Have you added any Adhoc Food in simulator?

**Comment by nithyaasworld** [comment] 2017-02-11 02:39
@coderReview No. NO adhoc food was added in simulator.

**Comment by nithyaasworld** [comment] 2017-02-11 18:24
Paulo ~

voice message associated with snap-photo food product is not syncing to db if I have my device time 1.15hrs ahead of actual time.

Steps to reproduce:

1. In iPad, set the time to 1.15hrs ahead of actual time.
2. Add some food item for the user "Sync Test"
3. Then logout and login to simulator (this has correct time) with the same user
4. Add some food item including adhoc foods
5. Logout of simulator and login back in ipad
6. add a snap a photo food product with comments and voice message
7. logout and generate a report for this user

Actual: 

snap photo food product's voice message is not seen in the generated in the iPad.
However when I login back to iPad, I can still see the voice message for that food product.

Expected:

Voice message should get synced too.

**Comment by coderReview** [comment] 2017-02-12 05:56
@rsial2 it seems that we have a race condition when making many changes to a Food Record before it gets synced to the server.
For now I would like to use a simple solution to fix this issue. That is to add a loading spinner to the Food Record consumption cell. This won't block any other functionality. You can continue to add new food records and use the rest of the application.

Please confirm. CC @szwart

**Comment by coderReview** [comment] 2017-02-12 06:09
Video.

[video.mov.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/769112/video.mov.zip)

**Comment by nithyaasworld** [comment] 2017-02-12 09:59
I tried the new code from your repo. Sometimes, It is stuck with the message "Uploading to Server"

It happens mostly in the following scenario:

(In iPad, it is 1.15hrs faster than actual time. In simulator, it has correct time)

1. Login with iPad and add some food product into consumption list and Logout
2. Now Login with simulator, add new food product via the mic icon (intake from voice). Now click on the added food product and add some comments or change quantity. Observe that it is stuck with the message "uploading to server" until I add another new food or logout.

The same scenario applies to iPad too.

iPad log: 
[ipad log.rtf.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/769193/ipad.log.rtf.zip)

simulator log: 
[system.log.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/769194/system.log.zip)


But the food item and changes are properly synced. Only the message "uploading to server" is not disappearing.

**Comment by nithyaasworld** [comment] 2017-02-13 09:25
Thanks Paulo for fixing the above issues.

There is one thing:

Sync is not happening in the following scenario, so ipad app user is able to add food products for the user who is already deleted.

1. In ipad, create a new user and add some food products and logout (note that iPad time is 1.15hrs ahead of actual time)
2. In simulator, login as the same user and add some more food products and logout (note that simulator has current time)
3. Delete this user in Admin Tool from Users tab
4. In iPad, login as this deleted-user and add some food products and observe

Actual:

User is able to login to the deleted-user in iPad and add foodproducts too.

Expected:

User should not be able to add food products to deleted user.

iPad log: 
[2.zip](https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/files/770557/2.zip)

**Comment by nithyaasworld** [comment] 2017-02-13 09:28
In the above case, Once I add a food product as a deleted-user in iPad, the deleted user is put back to Users tab from Delete tab in Admin Tool.

**Comment by coderReview** [comment] 2017-02-13 10:02
Hi, this scenario can't be fixed with a more complex solution and from the conversation above we can expect all iPads will be synchronized in time. Although not desirable no data is lost in the scenario above. Thanks

**Comment by nithyaasworld** [comment] 2017-02-13 10:17
@szwart The problem (stated here: https://github.com/NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker/issues/138#issuecomment-279333833 ) happens only when user is marked for deletion (that is, deleted from Users tab of Admin Tool and moved to Delete Tab). If the user is deleted (that is, removed from Delete tab too), then there is no such issue. iPad user is prevented from logging in if the user is already deleted.

Please confirm if the above is okay (as it happens only when the device time is not synchronised)

**Comment by nithyaasworld** [comment] 2017-02-13 10:45
@coderReview 

2--> I remember we discussed this already. But just forgot what we concluded about that issue.

Scenario is:
1- My iPad device time set to 1.15hrs. 
2. Created a new user and added some food consumption to this user and logged out
3. Logged into simulator as the same user and added some more food and logged out
4. Then I deleted all the old foods in the Food inventory by replacing it with just 15 foods
(Imported csv file with just 15 files and marked the checkbox to delete old entries during the upload)
5. Now in iPad, I still see all the food items (around 700 entries)
6. But in simulator, it correctly displays just 15 records.

**Comment by coderReview** [comment] 2017-02-13 13:27
> 5. Now in iPad, I still see all the food items in Food Inventory list (around 700 entries)

That is correct. Since the iPad clock is ahead of time it doesn't fetch the last changes.

There are two possible solutions for the clock issues:

1- Keep the sync time in server and make the device read this time instead of local clock. 

- Pro: nothing
- Cons: need to write new code to handle this. iPad clock will still have incorrect time.

2- Use a NTP server to keep clock synchronized in devices

- Pro: no change in code is needed. iPad clock gets adjusted
- Cons: clock won't get synchronized if server is down (this can be mitigated if the ntp server is the web server)

Since **2** is already implemented I don't see any point in adding more complexity to the application itself. I've added a 10 minutes offset to cope with any clock drift for long periods without synchronizing (for normal RTC clocks, one moth without synchronizaton would produce a 4 minutes clock drift).

**Comment by coderReview** [comment] 2017-02-13 13:32
@rsial2 and @nithyaasworld if the only issue you are seeing is related to the clock not being adjusted please check my previous comment.

@rsial2, @szwart please confirm solution **2- Use a NTP server to keep clock synchronized in devices** is enough to handle clock issues.

**Comment by szwart** [comment] 2017-02-13 13:42
We are fine with solution 2.  Thanks!

**Comment by rsial2** [comment] 2017-02-13 23:33
Thanks @szwart.

@coderReview, when will this ticket be completed?

CC @nithyaasworld

**Comment by coderReview** [comment] 2017-02-14 01:36
With this confirmation from @szwart I believe all issues are fixed. Just waiting final confirmation from @nithyaasworld

**Comment by nithyaasworld** [comment] 2017-02-14 13:49
@rsial2 This is verified with Paulo's repo. Once the code for "loading indicator" is merged to this Repo, I would like to do one final test to make sure everything is ok.

**Comment by nithyaasworld** [comment] 2017-02-14 19:18
Data sync issue is verified.

I have my device time setup as **5 mins faster than actual time** (within the 10 mins tolerance limit). Data got synced successfully.

Along with the above, the following also verified to make sure nothing is broken.

- Food Data CSV upload
- Delete Functionality
- Report Generation
- Automation Upload

**Comment by rsial2** [comment] 2017-02-14 20:22
Closing this issue.

FYI @szwart see above.

**Closed by rsial2** 2017-02-14 20:22 UTC
Labels: QA Verified, Round 12

**Comment by szwart** [comment] 2017-02-14 20:33
Thanks!
