### ISSUE TITLE
Round 10 - Food Inventory

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#113] opened 2016-03-18 19:13 UTC
1. Log in
2. Click Add Food (inventory button)
3. Search for Pork w/Potatoes in the search foods area at the top of the screen.
4. There is a message that comes up telling me that food is not in the inventory...but it is in the inventory.
5. Search for that food item using the search/pencil icon on the Daily intake Report screen and it will appear.  

That food item should appear in the Food Inventory search feature.

**Comment by coderReview** [comment] 2016-03-21 16:53
Was this search made after this item was deleted?

**Comment by szwart** [comment] 2016-03-21 16:59
The item had already been deleted in the data.csv file when we performed the search.   This happened for any food item that is listed as deleted in the data.csv file (this was not unique to the Pork w/Potatoes - that was just one example).  We are wondering if an easy fix would be to just delete the entire row of food in the data.csv file that was intended to be deleted.

**Comment by coderReview** [comment] 2016-03-21 18:26
Actually the issue is in search/pencil icon on the Daily intake Report screen. This search should not return deleted food items.
If you delete the row from the Data.csv file it won't be possible to determine if the food item was deleted or not. 
Could you share the data.csv with the food after they were deleted?

**Comment by szwart** [comment] 2016-03-21 19:31
Here is our data.csv file.  Please note this is confidential - please do not share with the entire TopCoder community.  Thanks!

**Comment by coderReview** [comment] 2016-03-21 19:33
Hi,
The file was not attached to the email.
Thanks
Paulo

Em Seg, 21 de mar de 2016 16:31, szwart <notifications@github.com> escreveu:

**Comment by szwart** [comment] 2016-03-21 19:36
It’s saying I can’t attach a .csv file.  Can I email it to you directly?

**Comment by coderReview** [comment] 2016-03-21 19:37
Yes. No problem.
Thanks

Em Seg, 21 de mar de 2016 16:36, szwart <notifications@github.com> escreveu:

**Comment by rsial2** [comment] 2016-03-21 19:40
Just a reminder folks that this Github project is public, please do not post anything to Github that you wouldn't want made public, including the referenced CSV file above :)

Emailing the files will work tho :)

**Comment by coderReview** [comment] 2016-03-23 21:20
I see that you mention in the issue text "Pork w/Potatoes" without a space between the slash and Potatoes. However the food name is "Pork w/ Potatoes". I've made some tests and could not reproduce this issue. I've loaded the file without any food deleted. There 745 food items. I then applied the sent csv file. The result count is 740 food items.

**Comment by szwart** [comment] 2016-03-23 21:32
So when you type Pork w/ Potatoes after selecting the Pencil/search icon, you don’t see two entries for that item?  I’m seeing two entries in the drop down box that appears when I am typing those words, and when I select either one, it lists the one with 385 calories in the Daily Intake Report (which is the one that is not deleted in the data.csv file).  So, it’s selecting the right one…I’m just not sure why it’s appearing twice in the Food Inventory and in the pencil/search area.

**Comment by coderReview** [comment] 2016-03-23 22:19
How many food items do you have in Admin Tool? Are there 740? This is number of food items if you apply the file you sent to me.

**Comment by coderReview** [comment] 2016-03-23 22:20
I don't see duplicated entries.

**Comment by coderReview** [comment] 2016-03-24 04:20
@szwart could you give me the exact details on how you load the food data? You can send me by email, with any other file you have used.
What I did on my side was:

1- Remove all entries with removed marked as YES.
2- Loaded the modified file. Number of records: 745.
3- Open iPad app and check the data. Only one record for Pork w/ Potatoes.
4- Loaded the original file. Number of records: 740.
5- Open iPad app and check the data. Only one record for Pork w/ Potatoes.

Thanks

**Comment by szwart** [comment] 2016-03-25 13:03
Paulo,

I just deleted all of the entries marked as YES in my data.csv file.  Then uploaded the modified file (the file contains 745 entries).  Then, when I go to the Food Data tab, the bottom line of that screen says there are 1098 entries.  I typed “Pork w” in the Filter records box, and now there are 4 Pork w/ Potatoes showing up.  There are 2 with a space after w/ and 2 without that space.  I’m beginning to think that whenever we make changes to the data.csv file, the original entries are still showing up here and are not truly deleted, even when I bulk upload a new data.csv file and those entries are not in the new file.  Is there a way to delete all foods before I bulk import?

Thanks,
Sara

**Comment by rsial2** [comment] 2016-03-25 13:21
We need to fix it so duplicates do not occur. Deleting all foods before bulk upload is not a best practice, has it may delete foods that are added on ad hoc basis

**Comment by szwart** [comment] 2016-03-25 13:35
Not sure if it helps, but we will always be adding foods using the bulk import function and not by adding on ad hoc basis, as that allows us to keep an inventory of what foods we have uploaded without looking them up individually.

**Comment by coderReview** [comment] 2016-03-25 13:53
What could be happening is that the name/origin are not exactly the same. The script that updates the data look for existing entry with exact name/origin after removing trailing spaces. If an entry already exists it will update this entry otherwise a new row will be inserted in the database. If you have a name with an space after the / and one without that will treated as two different food items.

**Comment by coderReview** [comment] 2016-03-25 13:56
@szwart when you uploaded the file without the removed items, there were some data inside the database. Could you try repeating your steps on a clean database?

**Comment by szwart** [comment] 2016-03-25 13:58
Copy.  However, I just bulk imported a data.csv file (after removing any foods marked as YES), and there are still 4 versions of that Pork w/ Potatoes in the food tab of the Admin Tool even though there is only 1 in the data.csv file.

**Comment by szwart** [comment] 2016-03-25 14:00
Sure…are you saying use a blank data.csv file?  Otherwise I don’t know how to clean the database that is already loaded in the Admin Tool.

**Comment by coderReview** [comment] 2016-03-25 16:25
Did Brian setup the database? Maybe he can help cleaning the database. Otherwise I can provide a script to delete everything. You would have to reinstall the iPad app.

**Comment by rsial2** [comment] 2016-03-25 16:28
Paulo, FYI Sara is testing in our test environment,not the one Brian setup.

Sara please let me know if i'm wrong.

**Comment by szwart** [comment] 2016-03-25 16:32
You are correct Rashid – I’m using your test environment.

**Comment by coderReview** [comment] 2016-03-25 17:50
@rsial2 my bad. I will clean it up then. Will let you know once I've finished.

**Comment by coderReview** [comment] 2016-03-25 18:54
@szwart, @rsial2 database has been cleaned up. Do the following:

1- Reinstall iPad app.
2- Remove all entries with removed marked as YES.
3- Loaded the modified file. Number of records: 745.
4- Open iPad app and check the data. Only one record for Pork w/ Potatoes.
5- Loaded the original file. Number of records: 740.
6- Open iPad app and check the data. Only one record for Pork w/ Potatoes.

Thanks

**Comment by szwart** [comment] 2016-03-28 13:10
Paulo,

This worked.  I’m seeing 745 foods in the Admin Tool and no duplicates when I scroll through the food inventory.

So from now it sounds like we should not have food items with the same name on different lines even though one may be marked with a YES and one with a NO.  Did you have to update any code, or can we fix this purely from the data.csv file and getting rid of the foods marked as YES?

Thanks very much!

Sara

**Comment by coderReview** [comment] 2016-03-28 13:31
@szwart There was no need for code change. 

The test database was not in good state (too many tests were done) and had some food items with similar names but with some extra spaces.

Since you have successfuly uploaded the file with no food marked with YES, you can now try the original CSV file you've sent me. You don't need to remove the rows with YES from the file. You just need to make sure that the row marked with NO comes after all other rows. 

<b>The script will always keep the last information found in the CSV file for a food item.</b>

**Comment by szwart** [comment] 2016-03-28 16:00
Paulo,

I bulk imported the CSV file with some foods marked as YES, and it worked!  There are no duplicates in the app or in the Admin Tool.

Thanks!!
Sara

**Comment by rsial2** [comment] 2016-03-28 17:26
Hi @szwart, can you please confirm that I can close this ticket.

**Closed** 2016-03-28 17:28 UTC
Labels: Round 10
