### ISSUE TITLE
Sync issue on the International Space Station (ISS FIT version 1.0)

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#190] opened 2017-03-08 15:12 UTC
Last month, a crewmember called down to report that she started getting an error message indicating that she was not connected to the Central Food Repository.  Her food logs were not being synced with the server and when the reports were generated at the end of the week, her data were missing (as expected since we knew her iPad was not syncing).  Around the same time, a 3rd crewmember on ISS manually registered himself as a user and his iPad was syncing fine.  When we told the first crewmember to start logging her intake on the 3rd crewmember's iPad, the sync error message came up again.  The ground team reloaded the user profiles and that apparently helped for a day (the iPads were able to sync again), but after that, they started getting the error message again.  After a week and a half, the ground team wiped and reloaded the app and it was working fine again for a few weeks.  Yesterday, we got a message indicating that the sync error message is there again.  I unfortunately can't reproduce the steps the crewmembers took before that happened because we learned about this 3rd hand.  The version of ISS FIT on ISS right now is the original version that was first released (not 2.0 or 3.0).  If it helps, here are some of the logs captured by the ground team:

With the verbose logging turned on for the database server, we are now seeing the following information in the logs when the crew attempts to connect:

LOG:  connection received: host=x.x.x.x port=x
LOG:  connection authorized: user=x database=x
ERROR:  value too long for type character varying(65536)
STATEMENT:  UPDATE data SET value = $2::varchar, modifieddate = 'now', modifiedby = $3::varchar WHERE id = $1::varchar
LOG:  could not receive data from client: Connection reset by peer

The log files repeat for several times with the above message as it looks like the iPad is trying over and over again to connect.

We realize you won't be able to reproduce this most likely, but we are wondering if you have a suggestion as to what the ground team or crew could try to resolve the issue?

**Comment by coderReview** [comment] 2017-03-08 15:36
please connect to the database using psql or any other program and run the following SQL command.

`ALTER TABLE data ALTER COLUMN value VARCHAR (10485760) NOT NULL;`

**Comment by coderReview** [comment] 2017-03-08 15:37
@szwart let me know if that works. Thanks

**Comment by szwart** [comment] 2017-03-08 15:52
I've relayed your message above - thanks!  I will let you know if we hear anything.  
FYI - we were told this error message came in this morning from the SQL database...not sure if this helps at all (it means nothing to me!):  
- ERROR: value too long for type character varying(65536)
- STATEMENT: UPDATE data SET value = $2::varchar, modifieddate = 'now', modifiedby = $3::varchar WHERE id = $1::varchar

**Comment by rsial2** [comment] 2017-03-08 16:23
@coderReview please review the item above. If we're good, then I'll close this ticket. Please confirm.

**Comment by coderReview** [comment] 2017-03-08 16:28
I believe with the above command the data will be able to saved to the database. From the error message the text data was too long for the column. @rsial2 If you want we can wait for a feedback before closing the issue. Just to point that the issue is not related to the latest version of the app.

**Comment by rsial2** [comment] 2017-03-08 17:35
It's an old version of the app, not the new version.

**Comment by szwart** [comment] 2017-03-08 17:49
Paulo,
The code you suggested did not work in their test lab. Here is their message:

Test failure.  Error: "ERROR: syntax error at or near "VARCHAR".  Maybe a syntax error in the FIT team's command?  Or maybe data set is required even though believed to be not required?  I'm not sure.  Probably best to not execute this Onboard until FIT team provides their feedback.  Command details:

sscadmin@ls1:~$ sudo su -
[ ~ ]:
root@ls1># sudo -u postgres psql -d pl_fit -U postgres
could not change directory to "/root"
psql (9.2.1)
Type "help" for help.

pl_fit=# ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT NULL;
ERROR:  syntax error at or near "VARCHAR"
LINE 1: ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT N...
                                            ^
pl_fit=#

On Mar 8, 2017, at 10:29 AM, Paulo Vitor Magacho <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe with the above command the data will be able to saved to the database. From the error message the text data was too long for the column. @rsial2<https://github.com/rsial2> If you want we can wait for a feedback before closing the issue. Just to point that the issue is not related to the latest version of the app.

**Comment by coderReview** [comment] 2017-03-08 17:53
@szwart there is something strange in the command.

What I sent is: `ALTER TABLE data ALTER COLUMN value VARCHAR(10485760) NOT NULL;`

What have been executed is: `ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT NULL;`

During copy paste this text appeared **<tel:10485760>** . It shouldn't be there.

**Comment by coderReview** [comment] 2017-03-08 17:54
@szwart let's treat this by email.

**Comment by rsial2** [comment] 2017-03-08 17:54
No let's keep this ticket open @coderReview and not use email

**Comment by coderReview** [comment] 2017-03-08 17:54
@rsial2 Ok.

**Comment by szwart** [comment] 2017-03-08 18:07
We are not seeing "10485760<tel:10485760>" in the error message. Here is the error message from the test lab again:

sscadmin@ls1:~$ sudo su -
[ ~ ]:
root@ls1># sudo -u postgres psql -d pl_fit -U postgres
could not change directory to "/root"
psql (9.2.1)
Type "help" for help.

pl_fit=# ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT NULL;
ERROR:  syntax error at or near "VARCHAR"
LINE 1: ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT N...
                                            ^
pl_fit=#

On Mar 8, 2017, at 11:55 AM, Paulo Vitor Magacho <notifications@github.com<mailto:notifications@github.com>> wrote:


@rsial2<https://github.com/rsial2> Ok.

**Comment by szwart** [comment] 2017-03-08 18:09
FYI - Cheryl thought is could be a permissions issue. This was the response when asked to run in root:
FIT's LS1 Postgres DB does not have a root user.  The "postgres" account is what's provisioned to administer the DB.  When testing with root, error" "psql: FATAL: Peer authentication failed for user "root"."

On Mar 8, 2017, at 11:55 AM, Paulo Vitor Magacho <notifications@github.com<mailto:notifications@github.com>> wrote:


@rsial2<https://github.com/rsial2> Ok.

**Comment by coderReview** [comment] 2017-03-08 18:11
You can do the following:
```bash
$ sudo su - postgres
$ psql -d pl_fit
pl_fit=# ALTER TABLE data ALTER COLUMN value VARCHAR (10485760) NOT NULL;
pl_fit=# \q
$ exit
```

**Comment by coderReview** [comment] 2017-03-08 18:16
@szwart this is from your message:

```text
pl_fit=# ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT NULL;
ERROR:  syntax error at or near "VARCHAR"
LINE 1: ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT N...
                                            ^
pl_fit=#

Check the text  inside the parenthesis. There is a number "10485760" and the text "<tel:10485760>".
```

**Comment by szwart** [comment] 2017-03-08 18:20
That is strange - I don't see what is in parentheses when I paste it. I'm currently in a meeting (about FIT!) and working off my phone.

I passed along your next suggestion. Thank you!!!

On Mar 8, 2017, at 12:16 PM, Paulo Vitor Magacho <notifications@github.com<mailto:notifications@github.com>> wrote:


@szwart<https://github.com/szwart> this is from your message:

pl_fit=# ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT NULL;
ERROR:  syntax error at or near "VARCHAR"
LINE 1: ALTER TABLE data ALTER COLUMN value VARCHAR (10485760<tel:10485760>) NOT N...
                                            ^
pl_fit=#

Check the text  inside the parenthesis. There is a number "10485760" and the text "<tel:10485760>".

**Comment by coderReview** [comment] 2017-03-08 18:22
@szwart maybe the cell is understanding 10485760 as cell phone and creates a link to it automatically. If this text ``<tel:10485760>`` is not being used in the command ok.

**Comment by szwart** [comment] 2017-03-08 19:32
They tried testing the code you posted above with no luck.  Here is the message from the ground team:

I don't know why the command has no output on the server TopCoder is testing on and has a syntax error on the LS1 I'm testing on.  This latest email is the same command but split up with one more return command to make the commands shorts.  I tested that and still syntax error.

[ ~ ]:
root@ls1># sudo su - postgres
[ ~ ]:
postgres@ls1>$ psql -d pl_fit
psql (9.2.1)
Type "help" for help.

pl_fit=# ALTER TABLE data ALTER COLUMN value VARCHAR (10485760) NOT NULL;
ERROR:  syntax error at or near "VARCHAR"
LINE 1: ALTER TABLE data ALTER COLUMN value VARCHAR (10485760) NOT N...
                                            ^
pl_fit=# \q
[ ~ ]:
postgres@ls1>$ exit
logout
[ ~ ]:
root@ls1>#

**Comment by coderReview** [comment] 2017-03-08 19:44
Sorry. My bad. I don't have access to the VM database to test, so I can't verify the commands.
Try this one:

```text
ALTER TABLE data ALTER COLUMN "value" TYPE VARCHAR(10485760);
```

**Comment by cflottorp** [comment] 2017-03-08 22:28
The above command works in the test development lab and I do not get an error message. 
However, does the server need to be re-started to take affect?

**Comment by coderReview** [comment] 2017-03-08 22:32
No. You don't need to restart the database server

**Comment by coderReview** [comment] 2017-03-08 22:33
If you want I can make more tests when I get home

**Comment by cflottorp** [comment] 2017-03-08 22:42
I get no errors but when I do a \d data the "public data" table still shows the value of (65536). 
![issfit_run](https://cloud.githubusercontent.com/assets/17480273/23727517/fcba8496-041d-11e7-99bf-be5ad96aad86.jpg) Just want to verify that nothing else is needed for verification.

**Comment by szwart** [comment] 2017-03-08 22:52
Thanks for your help with this today.  It sounds like the lab testing went well for this command, and they are waiting for a "GO" to implement tomorrow.  I will keep you posted.

**Comment by rsial2** [comment] 2017-03-09 00:08
Are you waiting on a GO from us @szwart? If yes, please proceed! We're all set and all of the latest code is in Github.

**Closed by rsial2** 2017-03-09 00:08 UTC

**Comment by coderReview** [comment] 2017-03-09 01:47
@cflottorp you missed a semicolon in the end of the command. otherwise the column is not update. And no error is thrown.

**Comment by coderReview** [comment] 2017-03-09 01:48
Just tested the command and it worked fine.
```text
postgres@ip-172-31-29-196:~$ psql -d pl_fit_old
psql (9.2.13)
Type "help" for help.

pl_fit_old=# ALTER TABLE data ALTER COLUMN value TYPE varchar(10000000);
ALTER TABLE
pl_fit_old=# \d data
                  Table "public.data"
    Column    |            Type             | Modifiers 
--------------+-----------------------------+-----------
 id           | character varying(64)       | not null
 name         | character varying(64)       | not null
 value        | character varying(10000000) | not null
 createdate   | timestamp without time zone | not null
 modifieddate | timestamp without time zone | not null
 modifiedby   | character varying(64)       | not null
Indexes:
    "data_pkey" PRIMARY KEY, btree (id)
Rules:
    syncdata_rule AS
    ON INSERT TO data DO  INSERT INTO sync_data (id, deviceid, type)  SELECT new.id, 
            devices.deviceid, 'object'
           FROM devices
          WHERE devices.deviceid::text <> new.modifiedby::text
    syncdata_update_rule AS
    ON UPDATE TO data DO  INSERT INTO sync_data (id, deviceid, type)  SELECT new.id, 
            devices.deviceid, 'object'
           FROM devices
          WHERE devices.deviceid::text <> new.modifiedby::text

pl_fit_old=# select value from data;
pl_fit_old=# 
```

**Comment by szwart** [comment] 2017-03-09 01:59
No, unfortunately someone else. But thanks 😀!! I'll keep you posted!

On Mar 8, 2017, at 6:09 PM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you waiting on a GO from us @szwart<https://github.com/szwart>? If yes, please proceed! We're all set and all of the latest code is in Github.

**Comment by szwart** [comment] 2017-03-10 22:50
Just wanted to let everyone know that Paulo's code fixed the sync issue they were currently having on ISS. Paulo, you and the Topcoder team are amazing!! We have a happy crew on ISS! Thank you!

On Mar 8, 2017, at 7:58 PM, Zwart, Sara (JSC-SK)[WYLE LABORATORIES, INC.] <sara.zwart-1@nasa.gov<mailto:sara.zwart-1@nasa.gov>> wrote:

No, unfortunately someone else. But thanks 😀!! I'll keep you posted!

On Mar 8, 2017, at 6:09 PM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you waiting on a GO from us @szwart<https://github.com/szwart>? If yes, please proceed! We're all set and all of the latest code is in Github.

**Comment by coderReview** [comment] 2017-03-10 23:20
Glad I could help 😀

**Comment by rsial2** [comment] 2017-03-10 23:22
That's great news!
